[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "deepagents>=0.2.8",
    "elastic-transport>=9.2.0",
    "elasticsearch>=9.2.0",
    "fastapi-mcp>=0.4.0",
    "fastapi[standard]>=0.122.0",
    "google-api-python-client>=2.187.0",
    "google-auth-oauthlib>=1.2.3",
    "langchain>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-google-community>=3.0.1",
    "langchain-google-genai>=3.2.0",
    "langchain-groq>=1.1.0",
    "langchain-mcp-adapters>=0.1.14",
    "langchain-tavily>=0.2.13",
    "markdownify>=1.2.2",
    "openpyxl>=3.1.5",
    "panadas>=0.2",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "python-pptx>=1.0.2",
    "streamlit>=1.51.0",
    "tavily>=1.1.0",
]
